name: "BiliHelper-personal"
on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'docker镜像tag:(多个tag用英文逗号分隔.[如:latest,2.0.0.1])'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build BiliHelper-personal Docker Image Build Stable Github
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: lkeme/bilihelper-personal
          dockerFile: docker/Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v7
          # platform: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          tag: ${{ github.event.inputs.docker_image_tag }}
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
