name: Tieba-Cloud-Sign

on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: 'docker镜像tag:(多个tag用英文逗号分隔.[如:latest,2.0.0.1])'
        required: true
        default: 'latest'
  schedule:
    - cron: 0 0 1 * *
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: tieba-cloud-sign

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tieba-Cloud-Sign
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Set Up Cache
        uses: actions/cache@v2
        id: buildx-cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx
      
      - 
        name: Buildx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Tieba-Cloud-Sign/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm,linux/s390x
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
